using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Media.ISO.SourceGenerators;

public sealed partial class BoxContentGenerator
{
    private static string GenerateSource(GenerationTarget target)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        var namespaceName = target.Symbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : target.Symbol.ContainingNamespace.ToDisplayString();

        var indentation = string.Empty;
        if (!string.IsNullOrEmpty(namespaceName))
        {
            builder.Append("namespace ").Append(namespaceName).AppendLine();
            builder.AppendLine("{");
            indentation = "    ";
        }

        builder.Append(indentation)
            .Append(GetAccessibilityKeyword(target.Symbol.DeclaredAccessibility))
            .Append(" partial class ")
            .Append(target.Symbol.Name);

        if (target.IsContainer)
        {
            builder.Append(" : global::").Append(ContainerBoxMetadataName);
        }
        else if (target.RequiresFullBoxBase)
        {
            builder.Append(" : global::").Append(FullBoxMetadataName);
        }

        builder.AppendLine()
            .Append(indentation)
            .AppendLine("{");

        if (target.IsContainer)
        {
            builder.Append(indentation).AppendLine("}");
            if (!string.IsNullOrEmpty(namespaceName))
            {
                builder.AppendLine("}");
            }

            return builder.ToString();
        }

        if (!target.ShouldGenerate || target.Properties.IsDefaultOrEmpty || target.Properties.Length == 0)
        {
            builder.Append(indentation).AppendLine("}");
            if (!string.IsNullOrEmpty(namespaceName))
            {
                builder.AppendLine("}");
            }

            return builder.ToString();
        }

        var memberIndent = indentation + "    ";
        var emittedSection = false;

        if (target.GenerateParse)
        {
            AppendParseMethod(builder, memberIndent, target.Properties);
            emittedSection = true;
        }

        if (target.GenerateWrite)
        {
            if (emittedSection)
            {
                builder.AppendLine();
            }

            AppendWriteMethod(builder, memberIndent, target.Properties);
            emittedSection = true;
        }

        if (target.GenerateContentSize)
        {
            if (emittedSection)
            {
                builder.AppendLine();
            }

            AppendContentSize(builder, memberIndent, target.Properties, target.IsFullBox);
            emittedSection = true;
        }

        if (emittedSection)
        {
            builder.AppendLine();
        }

        builder.Append(indentation).AppendLine("}");
        if (!string.IsNullOrEmpty(namespaceName))
        {
            builder.AppendLine("}");
        }

        return builder.ToString();
    }

    private static void AppendParseMethod(StringBuilder builder, string indent, IReadOnlyList<PropertyModel> properties)
    {
        builder.Append(indent)
            .Append("protected override long ParseBody(global::")
            .Append(ReaderMetadataName)
            .AppendLine(" reader, int depth)");
        builder.Append(indent).AppendLine("{");
        builder.Append(indent).AppendLine("    var __bytesRead = 0L;");
        builder.Append(indent).AppendLine("    var __remaining = (int)global::System.Math.Max(0L, Size - HeaderSize);");
        for (var __index = 0; __index < properties.Count; __index++)
        {
            var property = properties[__index];
            var __indent = indent + "    ";
            if (property.Accessor is StringPropertyAccessor __stringAccessor)
            {
                var __isLast = __index == properties.Count - 1;
                __stringAccessor.AppendRead(builder, __indent, property.Name, __isLast);
            }
            else
            {
                property.Accessor.AppendRead(builder, __indent, property.Name);
            }

            var sizeExpression = property.Accessor.GetSizeExpression(property.Name);
            builder.Append(indent)
                .Append("    var __size")
                .Append(__index)
                .Append(" = (long)(")
                .Append(sizeExpression)
                .AppendLine(");");
            builder.Append(indent)
                .Append("    __remaining -= (int)global::System.Math.Min(__size")
                .Append(__index)
                .AppendLine(", int.MaxValue);");
            builder.Append(indent)
                .Append("    __bytesRead += __size")
                .Append(__index)
                .AppendLine(";");
        }

        builder.Append(indent).AppendLine("    return __bytesRead;");
        builder.Append(indent).AppendLine("}");
    }

    private static void AppendWriteMethod(StringBuilder builder, string indent, IReadOnlyList<PropertyModel> properties)
    {
        builder.Append(indent)
            .Append("protected override long WriteBoxBody(global::")
            .Append(WriterMetadataName)
            .AppendLine(" writer)");
        builder.Append(indent).AppendLine("{");
        builder.Append(indent).AppendLine("    var __bytesWritten = 0L;");
        foreach (var property in properties)
        {
            property.Accessor.AppendWrite(builder, indent + "    ", property.Name);
            builder.Append(indent)
                .Append("    __bytesWritten += (long)(")
                .Append(property.Accessor.GetSizeExpression(property.Name))
                .AppendLine(");");
        }

        builder.Append(indent).AppendLine("    return __bytesWritten;");
        builder.Append(indent).AppendLine("}");
    }

    private static void AppendContentSize(StringBuilder builder, string indent, IReadOnlyList<PropertyModel> properties, bool isFullBox)
    {
        if (isFullBox)
        {
            builder.Append(indent).AppendLine("protected override int ContentSize =>");
            for (var i = 0; i < properties.Count; i++)
            {
                var property = properties[i];
                var sizeExpression = property.Accessor.GetSizeExpression(property.Name);
                builder.Append(indent)
                    .Append("    ");
                if (i > 0)
                {
                    builder.Append("+ ");
                }

                builder.Append(sizeExpression);
                builder.AppendLine(i == properties.Count - 1 ? ";" : string.Empty);
            }

            return;
        }

        builder.Append(indent).AppendLine("protected override long ComputeBodySize() =>");
        for (var i = 0; i < properties.Count; i++)
        {
            var property = properties[i];
            var sizeExpression = property.Accessor.GetSizeExpression(property.Name);
            builder.Append(indent)
                .Append("    ");
            if (i > 0)
            {
                builder.Append("+ ");
            }

            builder.Append("(long)(")
                .Append(sizeExpression)
                .Append(')');
            builder.AppendLine(i == properties.Count - 1 ? ";" : string.Empty);
        }
    }

    private static string GetAccessibilityKeyword(Accessibility accessibility) => accessibility switch
    {
        Accessibility.Public => "public",
        Accessibility.Internal => "internal",
        Accessibility.Protected => "protected",
        Accessibility.Private => "private",
        Accessibility.ProtectedAndInternal => "private protected",
        Accessibility.ProtectedOrInternal => "protected internal",
        _ => "internal"
    };
}
